module.exports = {
  myAuth: 'ADD YOUR AUTH CODE HERE',
  myDB: 'ADD DATABASE NAME AND THEN ADD PORT BELOW',
  myPort: 9599
  myEmail: 'WHERE YOU WANT YOUR EMAILS FROM SITE TO GO',
  myGmail: 'YOUR GMAIL CREDENTIALS FOR SENDING EMAILS',
  myPass: 'YOUR GMAIL PASSWORD'
  }


